{% set name = "scikit-base" %}
{% set version = "0.13.0" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 436c26067173a7235c465c64ac105008f6f889f09308c5e4e4a16e21c38c3ddc

build:
  noarch: python
  number: 0

requirements:
  host:
    - python {{ python_min }}
  run:
    - python >={{ python_min }}


outputs:
  - name: {{ name|lower }}
    build:
      noarch: python
      script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --no-index --no-compile
    requirements:
      host:
        - python {{ python_min }}
        - pip
        - setuptools
      run:
        - python >={{ python_min }},<3.15

    test:
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn >=0.24.0
        - python {{ python_min }}
      commands:
        - pip check
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate

  - name: {{ name|lower }}-all-extras
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }},<3.15
        - {{ pin_subpackage("scikit-base", exact=True) }}
        - pandas
        - numpy

    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn >=0.24.0
        - python {{ python_min }}

about:
  home: https://github.com/sktime/skbase
  summary: Base classes for sklearn-like parametric objects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://skbase.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skbase

extra:
  recipe-maintainers:
    - mcre-be
    - dhirschfeld
    - yarnabrina
    - fkiraly
