{% set name = "skbase" %}
{% set version = "0.4.3" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1cd29f974ae8b15a28e66a7547006387db3a8b5c8a520bcadb4083293b535976

build:
  number: 0
  # noarch: python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python

outputs:
  - name: {{ name|lower }}
    script: build_script.sh  # [unix]
    script: build_script.bat  # [win]
    requirements:
      build:
        - python                                 # [build_platform != target_platform]
        - cross-python_{{ target_platform }}     # [build_platform != target_platform]
      host:
        - python
        - pip
        - setuptools
      run:
        - python >=3.7,<3.12
        - scikit-learn >=0.24.0,<1.3.0
        - typing-extensions
        - pytest

    test:
      requires:
        - pip
      commands:
        - pip check
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate

  - name: {{ name|lower }}-all-extras
    build:
      noarch: python
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - python >=3.7,<3.12
        - {{ pin_subpackage("skbase", exact=True) }}
        - scikit-learn >=0.24.0,<1.3.0
        - typing-extensions
        - pytest
        - pandas
        - numpy

    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip

about:
  home: https://github.com/sktime/skbase
  summary: Base classes for sklearn-like parametric objects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://skbase.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skbase

extra:
  recipe-maintainers:
    - fkiraly
    - RNKuhns
