{% set name = "scikit-base" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}-suite
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: e175748b051b7b55f3b7713d53f5336ecfdfb42aa2f17aceb913b075511a8b33

build:
  number: 0
  skip: true  # [(py==37 and aarch64)]
  skip: true  # [py<37 or py>312]

requirements:
  build:
    - python
  host:
    - python
  run:
    - python

outputs:
  - name: {{ name|lower }}
    script: build_script.sh  # [unix]
    script: build_script.bat  # [win]
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - python >=3.7,<3.13

    test:
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn>=0.24.0
      commands:
        - pip check
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate

  - name: {{ name|lower }}-all-extras
    requirements:
      host:
        - python
        - pip
        - setuptools
      run:
        - python >=3.7,<3.13
        - {{ pin_subpackage("scikit-base", exact=True) }}
        - pandas
        - numpy

    test:
      imports:
        - skbase
        - skbase.base
        - skbase.lookup
        - skbase.testing
        - skbase.validate
      commands:
        - pip check
      requires:
        - pip
        - pytest
        - numpy
        - scipy
        - pandas
        - scikit-learn>=0.24.0

about:
  home: https://github.com/sktime/skbase
  summary: Base classes for sklearn-like parametric objects
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://skbase.readthedocs.io/en/latest/
  dev_url: https://github.com/sktime/skbase

extra:
  recipe-maintainers:
    - yarnabrina
    - fkiraly
    - RNKuhns
